spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**,/api/v1/admin/users/**,/api/v1/auth/**,/api/v1/admin/auth/**

            - id: timeslot-service
              uri: lb://timeslot-service
              predicates:
                - Path=/api/v1/restaurants/*/time-slots/**,/api/v1/admin/restaurants/*/time-slots/**

            - id: restaurant-service
              uri: lb://restaurant-service
              predicates:
                - Path=/api/v1/restaurants/**,/api/v1/admin/restaurants/**

            - id: reservation-service
              uri: lb://reservation-service
              predicates:
                - Path=/api/v1/reservations/**,/api/v1/admin/reservations/**

            - id: catalog-service
              uri: lb://catalog-service
              predicates:
                - Path=/api/v1/products/**
                - Method=GET

            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/api/v1/products/**,/api/v1/admin/products/**
                - Method=POST,PUT,PATCH,DELETE

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**,/api/v1/admin/orders/**

            - id: waiting-service
              uri: lb://waiting-service
              predicates:
                - Path=/api/v1/waitings/**,/api/v1/admin/waitings/**

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/v1/notifications/**,/api/v1/admin/notifications/**

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/v1/payments/**,/api/v1/admin/payments/**


server:
  port: 19000

jwt:
  secret: ${JWT_SECRET}

cors:
  allowed-origins: [ ]